# Generated by Django 4.0.2 on 2022-02-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, max_length=500, null=True)),
                ('search_result', models.CharField(blank=True, max_length=2000, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
